### ISSUE TITLE
Возможность фильтрации лога изменений

### ISSUE THREAD

**Issue by khorevaa** [KrapivinAndrey/ChangeLogGenerator#5]
Добавить возможность указания 2 массивов фильтров:
1. Включать строки только с указанным фильтров
2. Исключать строки с указанным фильтром.

Фильтр,
это строки в формате регулярного выражения, например
```
fix:*
```

**Comment by KrapivinAndrey** [comment]
Это предполагается сделать в будущем. В том, проекте на который ориентируюсь - используется yml файл для распределения коммитов по блокам.
Не уверен на счет регулярного выражения - обычно ориентируются на первое слово (что сделал: рефакторинг, багфикс, фикс и т.д.)
